#!/bin/bash

whichdialog = $(which whiptail)
zenityavailable = $(which zenity)
if [zenityavailable != "" ]
then

zenity --question --text="This malware is no joke! Do you want to proceed?" --title="WARNING!" --cancel-label="Cancel" --ok-label="Proceed"
zenity --question --text="This malware is no joke! Do you want to proceed? (Double Check)" --title="WARNING!" --cancel-label="Cancel" --ok-label="Proceed"
(
echo "10" ; sleep 1
echo "# Downloading necessary files" ;  sleep 1
echo "20" ; sleep 1
echo "# Resetting cron jobs" ; sleep 1
echo "50" ; sleep 1
echo "" ; sleep 1
echo "100" ; sleep 1
) |
zenity --progress \
  --width="100" \
  --height="100" \
  --title="Update System Logs" \
  --text="Scanning mail logs..." \
  --percentage=0
# export $PATH = ""
else

  if [ $(which apt) != ""]
  then

  

fi